### PR TITLE
Update zhTW/zhCN

### PR DESCRIPTION
**Pull request by EKE00372**

### CODE REVIEW

**Comment by EKE00372** [comment]
`Can't Show on Map in Combat`
when will this message show? It means: cannot set a pin on map in combat, or cannot show a pin on map in combat?

`Block Automatic World Quest Tracking when a Pin is Tracked`
It means "if a pin is tracking a world quest position already, disable this world quest tracking", or "block all world quest auto tracking when I'm using MapPinEnhanced"?

**Comment by EKE00372** [comment]
okay i saw localization page on curse. will fix translate at there.

**Comment by Nercus** [comment]
> Can't Show on Map in Combat
That message is shown when someone right-clicks a pin and selects "Show on Map". That will open the map where the pin is located and play a small highlighting animation.

> Block Automatic World Quest Tracking when a Pin is Tracked
People reported a problem, that if a pin is tracked and the player flies across a world quest area then the wq is tracked and the pin untracked.

**Comment by EKE00372** [comment]
Translate in curse localization, can import with next update, ty

**Pull request closed without merging**
